import pyssword
import time

password = pyssword.pyssword(prompt='Password: ')

if password != 0000:
    print("")
    print("ACCESS GRANTED!")
    print("")
    time.sleep(2)
    print("Hacking in progress... 10%")
    time.sleep(1.5)
    print("Hacking in progress... 20%")
    time.sleep(0.5)
    print("Hacking in progress... 30%")
    time.sleep(0.75)
    print("Hacking in progress... 40%")
    time.sleep(1.1)
    print("Hacking in progress... 50%")
    time.sleep(1.2)
    print("Hacking in progress... 60%")
    time.sleep(0.5)
    print("Hacking in progress... 70%")
    time.sleep(0.8)
    print("Hacking in progress... 80%")
    time.sleep(1.1)
    print("Hacking in progress... 90%")
    time.sleep(1)
    print("Hacking in progress... 100%")
    print("Hack complete!")
    time.sleep(5)